import 'enum/food_category.dart';
import 'model/menu.dart';

List<Menu> foodItems = [
  Menu(
    name: 'Spaghetti Carbonara',
    category: FoodCategory.dessert_category,
    price: 12.99,
    isSpicy: false,
    description: 'Classic Italian pasta with creamy sauce and pancetta.',
  ),
  Menu(
    name: 'Margherita Pizza',
    category: FoodCategory.food_category,
    price: 9.99,
    isSpicy: false,
    description: 'Pizza with fresh mozzarella, basil, and tomatoes.',
  ),
  Menu(
    name: 'Buffalo Wings',
    category: FoodCategory.food_category,
    price: 7.99,
    isSpicy: true,
    description: 'Spicy chicken wings served with blue cheese dip.',
  ),
  Menu(
    name: 'Caesar Salad',
    category: FoodCategory.food_category,
    price: 6.50,
    isSpicy: false,
    description: 'Crisp romaine lettuce with Caesar dressing and croutons.',
  ),
  Menu(
    name: 'Tom Yum Soup',
    category: FoodCategory.food_category,
    price: 8.99,
    isSpicy: true,
    description: 'Hot and sour Thai soup with shrimp and lemongrass.',
  ),
  Menu(
    name: 'Pad Thai',
    category: FoodCategory.food_category,
    price: 11.50,
    isSpicy: false,
    description: 'Stir-fried rice noodles with tofu, peanuts, and lime.',
  ),
  Menu(
    name: 'Cheeseburger',
    category: FoodCategory.food_category,
    price: 10.99,
    isSpicy: false,
    description: 'Beef patty with cheddar cheese, lettuce, and tomato.',
  ),
  Menu(
    name: 'Chicken Tikka Masala',
    category: FoodCategory.food_category,
    price: 13.99,
    isSpicy: true,
    description: 'Tender chicken in a creamy, spicy tomato sauce.',
  ),
  Menu(
    name: 'Sushi Platter',
    category: FoodCategory.food_category,
    price: 18.99,
    isSpicy: false,
    description: 'Assorted sushi and sashimi with soy sauce and wasabi.',
  ),
  Menu(
    name: 'Beef Tacos',
    category: FoodCategory.food_category,
    price: 9.50,
    isSpicy: true,
    description: 'Soft tacos with seasoned beef, lettuce, and salsa.',
  ),
  Menu(
    name: 'Falafel Wrap',
    category: FoodCategory.food_category,
    price: 7.99,
    isSpicy: false,
    description: 'Crispy falafel balls with tahini sauce in a flatbread.',
  ),
  Menu(
    name: 'Lamb Gyro',
    category: FoodCategory.food_category,
    price: 10.50,
    isSpicy: false,
    description: 'Slow-roasted lamb with tzatziki sauce in pita bread.',
  ),
  Menu(
    name: 'Pepperoni Pizza',
    category: FoodCategory.food_category,
    price: 10.50,
    isSpicy: false,
    description: 'Classic pizza with pepperoni and mozzarella cheese.',
  ),
  Menu(
    name: 'Clam Chowder',
    category: FoodCategory.food_category,
    price: 7.99,
    isSpicy: false,
    description: 'Creamy New England clam chowder with potatoes.',
  ),
  Menu(
    name: 'Chicken Caesar Wrap',
    category: FoodCategory.food_category,
    price: 8.99,
    isSpicy: false,
    description: 'Grilled chicken, romaine, and Caesar dressing in a wrap.',
  ),
  Menu(
    name: 'Kung Pao Chicken',
    category: FoodCategory.food_category,
    price: 12.99,
    isSpicy: true,
    description:
        'Stir-fried chicken with peanuts, chili peppers, and vegetables.',
  ),
  Menu(
    name: 'Shrimp Scampi',
    category: FoodCategory.food_category,
    price: 14.50,
    isSpicy: false,
    description: 'Shrimp sautéed in garlic, butter, and white wine sauce.',
  ),
  Menu(
    name: 'Veggie Burger',
    category: FoodCategory.food_category,
    price: 9.99,
    isSpicy: false,
    description: 'Plant-based patty with lettuce, tomato, and avocado.',
  ),
  Menu(
    name: 'Chicken Alfredo',
    category: FoodCategory.food_category,
    price: 13.50,
    isSpicy: false,
    description: 'Fettuccine pasta with grilled chicken in Alfredo sauce.',
  ),
  Menu(
    name: 'Fish and Chips',
    category: FoodCategory.food_category,
    price: 12.50,
    isSpicy: false,
    description: 'Crispy fried fish served with French fries and tartar sauce.',
  ),
];
